### ISSUE TITLE
Adicionar o nome do readme

### ISSUE THREAD

**Issue by Ruukaas** [Ruukaas/GCMS-Lucas-Henrique-Costa#1]
Add o nome ai pf
[readme] (https://github.com/Ruukaas/GCMS-Lucas-Henrique-Costa/blob/main/README.md)

**Comment by ramidedantas** [comment]
@Ruukaas, colocar o Readme no formato que está no meu respositório, depois me marque aqui.

**Comment by Ruukaas** [comment]
@ramidedantas ajustei o readme prof

**Comment by ramidedantas** [comment]
@Ruukaas Nome adicionado, pode fechar issue.
